### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by useragent23253** [MalwareHunters/vultriever#1]
python3 vultriever.py                                                                
  File "/home/host/Desktop/Pentest/vultriever-main/vultriever.py", line 260
    print logo
    ^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

Why is it happening?
Any suggestions?

**Comment by MalwareHunters** [comment]
Fixed. The code was originally written for Python 2. Now the script is executed correctly Python 3. Thanks!
